---
abstract: 'Base class for objects containing a list of items'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Container
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Complex: 0
  Data::Miscellany: 0
  perl: 5.6.0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Container
  homepage: http://search.cpan.org/dist/Data-Container/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/data-container.git
version: 0.07
