---
abstract: 'base class for objects containing a list of items'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  Test::Compile: 0
  Test::More: 0.70
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Container
no_index:
  directory:
    - inc
    - t
recommends:
  Test::Pod: 0
  Test::Pod::Coverage: 0
requires:
  Class::Accessor::Complex: 0
  Data::Miscellany: 0
  NEXT: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
