---
abstract: 'Base class for objects containing a list of items'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Container
provides:
  Data::Container:
    file: lib/Data/Container.pm
    version: 1.100840
requires:
  Carp: 0
  Class::Accessor::Complex: 0
  Data::Miscellany: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  overload: 0
  parent: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Container
  homepage: http://search.cpan.org/dist/Data-Container/
  repository: http://github.com/hanekomu/Data-Container
version: 1.100840
